### ISSUE TITLE
File does not exist and is not created automaticly

### ISSUE THREAD

**Issue by Gnaz8** [Gartenschlaeger/TitanProfessions#1]
Message: Couldn't open Interface\AddOns\TitanProfessions\TitanProfessions.xml
Time: Tue Jul 19 18:07:41 2022
Count: 3

**Comment by Gnaz8** [comment]
Downloaded TitanProfessions.xml from the Code page (its not in the zip)
new error 
Message: Interface\AddOns\TitanProfessions\TitanProfessions.xml(16): error: not well-formed (invalid token)
Time: Tue Jul 19 19:13:41 2022
Count: 3

**Comment by Gnaz8** [comment]
I guess the download on curseforge is old :D Replaced all files with the newest github version and it works like a charm.
Thanks for the mod :)

**Comment by ghost** [comment]
Hello Gnaz8,

thank you very much for your report. Indeed the xml file was missing in the final zip file for Curseforge.
I fixed the problem in beta4, so the official Curseforge version should work now.

Glad you are trying out this addon. If you have any other questions or feature requests, feel free to contact me.
